package api

import (
	"fmt"
	"net/http"
	"strings"
)

// installShHandler generates a curl-piped bash installer for Linux/macOS
// agents. The token + serverID are baked into the script, and the agent
// dial URL is derived from the calling request so reverse-proxied hubs
// produce correct WSS endpoints.
//
// IMPORTANT: in Phase 1 the script writes an agent config file and prints
// the manual command to run — it does NOT yet download a release binary.
// Once releases are wired (Phase 1.5) the script will fetch the right
// arch-specific binary and register a systemd unit automatically.
func installShHandler() http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		serverID, token, ok := requireInstallParams(w, r)
		if !ok {
			return
		}
		hubURL := wsBaseURL(hubBaseURL(r)) + "/agent"

		w.Header().Set("Content-Type", "text/x-shellscript")
		fmt.Fprint(w, renderInstallSh(hubURL, serverID, token))
	}
}

// installPs1Handler is the Windows counterpart. Same caveats — Phase 1.5
// will fold in binary download + sc.exe service registration.
func installPs1Handler() http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		serverID, token, ok := requireInstallParams(w, r)
		if !ok {
			return
		}
		hubURL := wsBaseURL(hubBaseURL(r)) + "/agent"

		w.Header().Set("Content-Type", "text/plain")
		fmt.Fprint(w, renderInstallPs1(hubURL, serverID, token))
	}
}

func requireInstallParams(w http.ResponseWriter, r *http.Request) (string, string, bool) {
	id := r.URL.Query().Get("id")
	token := r.URL.Query().Get("token")
	if id == "" || token == "" {
		http.Error(w, "# missing id or token", http.StatusBadRequest)
		return "", "", false
	}
	return id, token, true
}

func renderInstallSh(hubURL, serverID, token string) string {
	const tmpl = `#!/usr/bin/env bash
# ArgonWatchGo agent install — auto-generated by hub at install time.
# Re-running is safe; the config is overwritten and the service restarted.
set -euo pipefail

INSTALL_DIR="${INSTALL_DIR:-/opt/argon-watch}"
CONFIG_DIR="${CONFIG_DIR:-/etc/argon-watch}"
BINARY="${INSTALL_DIR}/argon-watch"
SERVICE_NAME="${SERVICE_NAME:-argon-watch-agent}"

mkdir -p "$INSTALL_DIR" "$CONFIG_DIR"

cat > "${CONFIG_DIR}/agent.config.json" <<EOF
{
  "hubUrl": "__HUB_URL__",
  "serverId": "__SERVER_ID__",
  "token": "__TOKEN__"
}
EOF
chmod 600 "${CONFIG_DIR}/agent.config.json"

# Binary download will land in Phase 1.5. For now, point the operator at
# the right command to run once they've placed argon-watch on the host.
if [ -x "$BINARY" ]; then
  cat > "/etc/systemd/system/${SERVICE_NAME}.service" <<UNIT
[Unit]
Description=ArgonWatchGo Agent
After=network.target

[Service]
Type=simple
ExecStart=${BINARY} --mode=agent --config=${CONFIG_DIR}/agent.config.json
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
UNIT
  systemctl daemon-reload
  systemctl enable --now "$SERVICE_NAME"
  echo "argon-watch agent: service installed and started"
else
  echo "argon-watch agent: config written to ${CONFIG_DIR}/agent.config.json"
  echo "  Place the argon-watch binary at ${BINARY} then re-run this installer,"
  echo "  or run manually:"
  echo "    argon-watch --mode=agent --config=${CONFIG_DIR}/agent.config.json"
fi
`
	r := strings.NewReplacer(
		"__HUB_URL__", hubURL,
		"__SERVER_ID__", serverID,
		"__TOKEN__", token,
	)
	return r.Replace(tmpl)
}

func renderInstallPs1(hubURL, serverID, token string) string {
	const tmpl = `# ArgonWatchGo agent install (Windows) — auto-generated by hub.
$ErrorActionPreference = 'Stop'

$InstallDir = if ($env:INSTALL_DIR) { $env:INSTALL_DIR } else { 'C:\Program Files\ArgonWatch' }
$ConfigDir  = if ($env:CONFIG_DIR)  { $env:CONFIG_DIR  } else { 'C:\ProgramData\ArgonWatch' }
$Binary     = Join-Path $InstallDir 'argon-watch.exe'
$ServiceName = 'ArgonWatchAgent'

New-Item -ItemType Directory -Force -Path $InstallDir, $ConfigDir | Out-Null

$cfg = @"
{
  "hubUrl": "__HUB_URL__",
  "serverId": "__SERVER_ID__",
  "token": "__TOKEN__"
}
"@
$cfgPath = Join-Path $ConfigDir 'agent.config.json'
Set-Content -Path $cfgPath -Value $cfg -Encoding UTF8

if (Test-Path $Binary) {
    if (Get-Service -Name $ServiceName -ErrorAction SilentlyContinue) {
        Stop-Service -Name $ServiceName -Force
        sc.exe delete $ServiceName | Out-Null
        Start-Sleep -Seconds 1
    }
    $binPath = '"' + $Binary + '" --mode=agent --config="' + $cfgPath + '"'
    sc.exe create $ServiceName binPath= $binPath start= auto | Out-Null
    Start-Service -Name $ServiceName
    Write-Host "argon-watch agent: service installed and started"
} else {
    Write-Host "argon-watch agent: config written to $cfgPath"
    Write-Host "  Place argon-watch.exe at $Binary and re-run this installer,"
    Write-Host "  or run manually:"
    Write-Host "    argon-watch --mode=agent --config=$cfgPath"
}
`
	r := strings.NewReplacer(
		"__HUB_URL__", hubURL,
		"__SERVER_ID__", serverID,
		"__TOKEN__", token,
	)
	return r.Replace(tmpl)
}
